### PR TITLE
Some typo fixes

### PR DESCRIPTION
**Pull request by nicopap**
the "while" to "wide" could also be "wild" or "white" but I felt "wide" was the most likely.

bulbul might be controversial, so feel free to revert the commit.

### CODE REVIEW

**Comment by acabal** [comment]
Have you checked these changes against the page scans?

Bulbul should remain capitalized as it's a kind of personification.

**Comment by nicopap** [comment]
Thanks for pointing it out! It turns out it is "whole"

**Comment by acabal** [comment]
Did you also check the other changes?

**Comment by nicopap** [comment]
All good now. Checked:

* "the rattle of the brazen"
* "the dying lustres"
* "the whole sweep"

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
